import { type ChartSpec } from "@/lib/chart-spec";

export const CHART_TYPE_META: Record<
  ChartSpec["type"],
  { label: string; emoji: string }
> = {
  weekly_pattern: { label: "Weekly pattern", emoji: "📅" },
  hourly_heatmap: { label: "Hourly heatmap", emoji: "🕒" },
  month_calendar: { label: "90-day calendar", emoji: "🗓" },
  booking_window: { label: "Booking window", emoji: "🎟" },
  stat_grid: { label: "Quick stats", emoji: "📊" },
  compare_zones: { label: "Zone comparison", emoji: "🆚" },
  donut_breakdown: { label: "Breakdown", emoji: "🍩" },
  seasonal_curve: { label: "Seasonal curve", emoji: "🌤" },
  conditions_calendar: { label: "Conditions calendar", emoji: "🌡" },
  sighting_probability: { label: "Sighting probability", emoji: "🐋" },
  departure_reliability: { label: "Departure reliability", emoji: "🛫" },
  price_curve: { label: "Price curve", emoji: "💶" },
  ticket_ladder: { label: "Ticket tiers", emoji: "🎫" },
  daily_pattern: { label: "Daily pattern", emoji: "⏰" },
  tribune_density: { label: "Tribune density", emoji: "🌊" },
  duration_profiles: { label: "Visit duration", emoji: "⏱" },
  entrance_lanes: { label: "Entrance lanes", emoji: "🚪" },
  co_bookings: { label: "Pairs with", emoji: "🔗" },
  zone_crowd_heatmap: { label: "Zone × hour crowd", emoji: "🗺" },
  zone_wait_heatmap: { label: "Zone × hour wait", emoji: "⏳" },
  golden_hour_match: { label: "Golden-hour match", emoji: "🌅" },
  savings_breakdown: { label: "Card savings", emoji: "💳" },
  return_buffer_rank: { label: "Return buffer", emoji: "🚢" },
  seat_value_map: { label: "Seat value", emoji: "🎭" },
  optimal_departure: { label: "Optimal slot", emoji: "🚁" },
  stop_frequency: { label: "Stop frequency", emoji: "🚌" },
  route_profile: { label: "Route profile", emoji: "🗺" },
  queue_compare: { label: "Queue compare", emoji: "🚪" },
  duration_stat: { label: "Duration stat", emoji: "⏱" },
  ride_wait_curve: { label: "Ride wait curve", emoji: "🎢" },
  activity_window: { label: "Activity window", emoji: "🦜" },
  opening_hour_rank: { label: "Rope-drop rank", emoji: "🏁" },
  daily_programme: { label: "Daily programme", emoji: "📋" },
  time_split: { label: "Time split", emoji: "⏳" },
  history_timeline: { label: "History timeline", emoji: "🏛" },
  slot_compare: { label: "Slot compare", emoji: "🌅" },
  ticket_access_matrix: { label: "Ticket access matrix", emoji: "🎫" },
  duration_budget: { label: "Duration budget", emoji: "⏱" },
  landmark_coverage: { label: "Landmark coverage", emoji: "🗺" },
  itinerary_flow: { label: "Itinerary flow", emoji: "🚶" },
  best_for_matrix: { label: "Best-for matrix", emoji: "🎯" },
  season_weather_fit: { label: "Season & weather fit", emoji: "🌤" },
  entrance_map: { label: "Entrance map", emoji: "🚪" },
  floor_plan_flow: { label: "Floor-plan flow", emoji: "🗺" },
  rules_checklist: { label: "Rules checklist", emoji: "📜" },
  transit_options: { label: "Transit options", emoji: "🚇" },
  time_value_matrix: { label: "Time-value matrix", emoji: "⏳" },
  accessibility_guide: { label: "Accessibility guide", emoji: "♿" },
};
