/**
 * Full Headout taxonomy — parsed from the canonical TSV the CMS team works
 * against. Subcategories without a numeric Headout id (currently just
 * "Whale watching" under Cruises) are given a stable synthetic id derived
 * from the slug.
 */

import type { HeadoutCategoryRecord } from "./types";

export const HEADOUT_CATEGORIES: HeadoutCategoryRecord[] = [
  {
    categoryId: 1,
    categoryName: "Tickets",
    subcategories: [
      { subcategoryId: 1007, subcategoryName: "Landmarks" },
      { subcategoryId: 1002, subcategoryName: "Museums" },
      { subcategoryId: 1001, subcategoryName: "Theme Parks" },
      { subcategoryId: 1005, subcategoryName: "Water Parks" },
      { subcategoryId: 1003, subcategoryName: "Zoos" },
      { subcategoryId: 1140, subcategoryName: "Aquariums" },
      { subcategoryId: 1098, subcategoryName: "Observation Decks" },
      { subcategoryId: 1008, subcategoryName: "City Cards" },
      { subcategoryId: 1004, subcategoryName: "Parks" },
      { subcategoryId: 1006, subcategoryName: "Religious Sites" },
      { subcategoryId: 1149, subcategoryName: "Immersive Experiences" },
    ],
  },
  {
    categoryId: 2,
    categoryName: "Tours",
    subcategories: [
      { subcategoryId: 1010, subcategoryName: "Guided Tours" },
      { subcategoryId: 1143, subcategoryName: "Day Trips" },
      { subcategoryId: 1012, subcategoryName: "City Tours" },
      { subcategoryId: 1009, subcategoryName: "Walking Tours" },
      { subcategoryId: 1011, subcategoryName: "Hop-on Hop-off Tours" },
      { subcategoryId: 1013, subcategoryName: "Private Tours" },
      { subcategoryId: 1014, subcategoryName: "Bike & Segway Tours" },
      { subcategoryId: 1068, subcategoryName: "Speed Boat Tours" },
      { subcategoryId: 1147, subcategoryName: "Heritage Experiences" },
      { subcategoryId: 1017, subcategoryName: "Photography Tours" },
      { subcategoryId: 1016, subcategoryName: "Multi-Day Tours" },
      { subcategoryId: 1015, subcategoryName: "Shopping" },
      {
        subcategoryId: 1018,
        subcategoryName: "Port of Call Tours (Cruise Visitors)",
      },
    ],
  },
  {
    categoryId: 3,
    categoryName: "Transportation",
    subcategories: [
      { subcategoryId: 1019, subcategoryName: "Airport Transfers" },
      { subcategoryId: 1145, subcategoryName: "Shared Airport Transfers" },
      { subcategoryId: 1022, subcategoryName: "Public Transport" },
      { subcategoryId: 1021, subcategoryName: "Attraction Transfers" },
      { subcategoryId: 1144, subcategoryName: "Private Airport Transfers" },
      { subcategoryId: 1108, subcategoryName: "Ferry Tickets" },
      { subcategoryId: 1133, subcategoryName: "Train Tickets" },
      { subcategoryId: 1139, subcategoryName: "Train Passes" },
      { subcategoryId: 1020, subcategoryName: "Car Rentals" },
    ],
  },
  {
    categoryId: 4,
    categoryName: "Travel Services",
    subcategories: [
      { subcategoryId: 1023, subcategoryName: "Wifi & SIM Cards" },
      { subcategoryId: 1132, subcategoryName: "Airport Services" },
      { subcategoryId: 1153, subcategoryName: "Luggage Storage" },
    ],
  },
  {
    categoryId: 5,
    categoryName: "Food & Drink",
    subcategories: [
      { subcategoryId: 1025, subcategoryName: "Dining" },
      { subcategoryId: 1026, subcategoryName: "Food Tours" },
      { subcategoryId: 1028, subcategoryName: "Wineries" },
      { subcategoryId: 1027, subcategoryName: "Cooking Classes" },
      { subcategoryId: 1030, subcategoryName: "Pub Crawls" },
      { subcategoryId: 1031, subcategoryName: "Food Passes" },
      { subcategoryId: 1029, subcategoryName: "Coffee & Tea" },
    ],
  },
  {
    categoryId: 7,
    categoryName: "Entertainment",
    subcategories: [
      { subcategoryId: 1037, subcategoryName: "Plays" },
      { subcategoryId: 1041, subcategoryName: "Comedy" },
      { subcategoryId: 1107, subcategoryName: "Drama" },
      { subcategoryId: 1036, subcategoryName: "Musicals" },
      { subcategoryId: 1100, subcategoryName: "Dance Shows" },
      { subcategoryId: 1038, subcategoryName: "Opera" },
      { subcategoryId: 1047, subcategoryName: "Family Shows" },
      { subcategoryId: 1040, subcategoryName: "Classical Concerts" },
      { subcategoryId: 1119, subcategoryName: "Theatrical Concerts" },
      { subcategoryId: 1148, subcategoryName: "Nightlife" },
      { subcategoryId: 1042, subcategoryName: "Sports" },
      { subcategoryId: 1043, subcategoryName: "Cabarets" },
      { subcategoryId: 1104, subcategoryName: "Immersive Theatre" },
      { subcategoryId: 1046, subcategoryName: "New Arrivals" },
      { subcategoryId: 1105, subcategoryName: "Circus" },
      { subcategoryId: 1106, subcategoryName: "Fantasy" },
      { subcategoryId: 1044, subcategoryName: "Ballet" },
      { subcategoryId: 1120, subcategoryName: "Rock Concerts" },
      { subcategoryId: 1151, subcategoryName: "Adult Shows" },
      { subcategoryId: 1096, subcategoryName: "Pantomimes" },
      { subcategoryId: 1103, subcategoryName: "Magic Shows" },
      { subcategoryId: 1039, subcategoryName: "Cinema" },
      { subcategoryId: 1121, subcategoryName: "Church Concerts" },
      { subcategoryId: 1045, subcategoryName: "Shows Opening Soon" },
      { subcategoryId: 1048, subcategoryName: "Shows Reopening" },
      { subcategoryId: 1097, subcategoryName: "See it in Style" },
    ],
  },
  {
    categoryId: 8,
    categoryName: "Adventure",
    subcategories: [
      { subcategoryId: 1056, subcategoryName: "Outdoor Activities" },
      { subcategoryId: 1055, subcategoryName: "Indoor Adventure" },
      { subcategoryId: 1073, subcategoryName: "Desert Safari" },
      { subcategoryId: 1052, subcategoryName: "Ziplining" },
      { subcategoryId: 1049, subcategoryName: "Skydiving" },
      { subcategoryId: 1134, subcategoryName: "Go Karting" },
      { subcategoryId: 1116, subcategoryName: "Mountain Excursions" },
      { subcategoryId: 1135, subcategoryName: "Quad Biking" },
      { subcategoryId: 1053, subcategoryName: "Climbing" },
      { subcategoryId: 1054, subcategoryName: "Racing" },
      { subcategoryId: 1114, subcategoryName: "Sledding" },
      { subcategoryId: 1050, subcategoryName: "Skiing" },
      { subcategoryId: 1051, subcategoryName: "Bungee Jumping" },
      { subcategoryId: 1115, subcategoryName: "Snowshoeing" },
      { subcategoryId: 1113, subcategoryName: "Snowboarding" },
    ],
  },
  {
    categoryId: 9,
    categoryName: "Aerial Sightseeing",
    subcategories: [
      { subcategoryId: 1057, subcategoryName: "Helicopter Tours" },
      { subcategoryId: 1112, subcategoryName: "Cable Car Tours" },
      { subcategoryId: 1058, subcategoryName: "Hot Air Balloon" },
      { subcategoryId: 1059, subcategoryName: "Airplane Tours" },
    ],
  },
  {
    categoryId: 10,
    categoryName: "Water Sports",
    subcategories: [
      { subcategoryId: 1101, subcategoryName: "Snorkeling" },
      { subcategoryId: 1065, subcategoryName: "Kayaking" },
      { subcategoryId: 1066, subcategoryName: "Rafting" },
      { subcategoryId: 1067, subcategoryName: "Boat Rentals" },
      { subcategoryId: 1062, subcategoryName: "Scuba Diving" },
      { subcategoryId: 1064, subcategoryName: "Jet Skiing" },
      { subcategoryId: 1063, subcategoryName: "Surfing" },
      { subcategoryId: 1102, subcategoryName: "Marine Walks" },
      { subcategoryId: 1138, subcategoryName: "Paddle Sport" },
    ],
  },
  {
    categoryId: 11,
    categoryName: "Nature & Wildlife",
    subcategories: [
      { subcategoryId: 1070, subcategoryName: "Safari" },
      { subcategoryId: 1071, subcategoryName: "Hiking & Trails" },
      { subcategoryId: 1072, subcategoryName: "Camping" },
    ],
  },
  {
    categoryId: 12,
    categoryName: "Wellness",
    subcategories: [
      { subcategoryId: 1074, subcategoryName: "Spa" },
      { subcategoryId: 1117, subcategoryName: "Baths" },
      { subcategoryId: 1075, subcategoryName: "Fitness Passes" },
    ],
  },
  {
    categoryId: 13,
    categoryName: "Classes",
    subcategories: [{ subcategoryId: 1099, subcategoryName: "Workshops" }],
  },
  {
    categoryId: 14,
    categoryName: "Specials",
    subcategories: [
      { subcategoryId: 1080, subcategoryName: "Combos" },
      { subcategoryId: 1111, subcategoryName: "Valentine's Day" },
      { subcategoryId: 1079, subcategoryName: "Digital Experiences" },
      { subcategoryId: 1081, subcategoryName: "Coming Soon" },
    ],
  },
  {
    categoryId: 16,
    categoryName: "Staycations",
    subcategories: [
      { subcategoryId: 1090, subcategoryName: "Wildlife Staycations" },
      { subcategoryId: 1089, subcategoryName: "Mountains Staycations" },
      { subcategoryId: 1088, subcategoryName: "Beach Staycations" },
      { subcategoryId: 1091, subcategoryName: "National Park Staycations" },
    ],
  },
  {
    categoryId: 18,
    categoryName: "Cruises",
    subcategories: [
      { subcategoryId: 1061, subcategoryName: "Sightseeing Cruises" },
      { subcategoryId: 1060, subcategoryName: "Dinner Cruises" },
      { subcategoryId: 1094, subcategoryName: "Lunch Cruises" },
      {
        subcategoryId: "synthetic:cruises:whale-watching",
        subcategoryName: "Whale watching",
      },
    ],
  },
  {
    categoryId: 19,
    categoryName: "Sports",
    subcategories: [
      { subcategoryId: 1109, subcategoryName: "Formula 1" },
      { subcategoryId: 1131, subcategoryName: "Baseball" },
      { subcategoryId: 1130, subcategoryName: "Muay Thai" },
      { subcategoryId: 1110, subcategoryName: "Football" },
    ],
  },
];
