// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/busy-chart/WeeklyPattern.tsx": () => import("../components/mockups/busy-chart/WeeklyPattern.tsx"),
  "./components/mockups/viz-studio-home/Atlas.tsx": () => import("../components/mockups/viz-studio-home/Atlas.tsx"),
  "./components/mockups/viz-studio-home/StudioToday.tsx": () => import("../components/mockups/viz-studio-home/StudioToday.tsx"),
  "./components/mockups/viz-studio-home/Workbench.tsx": () => import("../components/mockups/viz-studio-home/Workbench.tsx")
};
