import {
  pgTable,
  text,
  serial,
  timestamp,
  integer,
  jsonb,
  boolean,
} from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";
import { cesTable } from "./ces";

export const chartsTable = pgTable("charts", {
  id: serial("id").primaryKey(),
  ceId: integer("ce_id")
    .notNull()
    .references(() => cesTable.id, { onDelete: "cascade" }),
  slug: text("slug").notNull(),
  question: text("question").notNull(),
  title: text("title").notNull(),
  subtitle: text("subtitle").notNull().default(""),
  insight: text("insight").notNull().default(""),
  chartType: text("chart_type").notNull(),
  spec: jsonb("spec").notNull().$type<Record<string, unknown>>(),
  /**
   * "draft" — generated by the research-grounded pipeline, awaiting writer
   * review. "published" — live and embeddable. Legacy and curated rows
   * default to "published" so existing behaviour is preserved.
   */
  status: text("status").notNull().default("published"),
  /**
   * Provenance metadata produced by the research-grounded pipeline.
   * Optional — legacy rows have `null`. Shape is intentionally loose to
   * allow per-archetype variations without DB migrations.
   *
   * Common fields used by the UI/admin:
   *  - status: "drd_grounded" | "web_grounded" | "estimated"
   *  - drd_snippets: string[]
   *  - web_sources: { title, url }[]
   *  - estimates: { field, reasoning }[]
   *  - verifier_notes: string
   */
  provenance: jsonb("provenance").$type<Record<string, unknown> | null>(),
  /** Last time a writer (not the AI pipeline) edited this chart. */
  lastEditedByWriterAt: timestamp("last_edited_by_writer_at", {
    withTimezone: true,
  }),
  /**
   * Whether interactive affordances (locked detail panels, hover popovers,
   * focus-pill clicks, etc.) are enabled when this chart is embedded.
   * Defaults to `true` for parity with existing behaviour. Writers can flip
   * this off for embeds that should render as static visuals only — useful
   * for archetypes whose locked panels aren't yet content-complete.
   */
  interactive: boolean("interactive").notNull().default(true),
  /**
   * Page-type-aware metadata (research pipeline v2). Optional — legacy and
   * v1 rows have `null`. Identifies which page deck (e.g. "plan-your-visit",
   * "skip-the-line") a chart was generated for and which section slot it
   * fills inside that deck.
   */
  pageType: text("page_type"),
  sectionId: text("section_id"),
  /**
   * Editorial overlay produced by the v2 pipeline alongside the chart spec.
   * Shape mirrors `EDITORIAL_OVERLAY_PROMPT`: headline, subheadline, cta,
   * confidence, tip, warning, personalizationNote. Optional for v1 rows.
   */
  editorial: jsonb("editorial").$type<Record<string, unknown> | null>(),
  /**
   * Optional writer-editable editorial overlay copy for the Studio CE detail
   * page. When set, `assembleHybridOverlay` prefers these over the chart
   * spec's title/subtitle/insight so writers can sharpen page-level wording
   * without changing what embeds show. Null = fall back to the chart spec.
   */
  overlayHeadline: text("overlay_headline"),
  overlaySubhead: text("overlay_subhead"),
  overlayInsight: text("overlay_insight"),
  /**
   * Task #151 — render-time presentation overrides (palette, view, emphasis,
   * direction, density). Applied by chart components at render-time only;
   * never triggers a re-generation. Nullable for back-compat with rows
   * predating this column. Shape mirrors `PresentationOverrides` in
   * `artifacts/viz-studio/src/lib/presentation.ts`.
   */
  presentation: jsonb("presentation").$type<Record<string, unknown> | null>(),
  sortOrder: integer("sort_order").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
});

export const insertChartSchema = createInsertSchema(chartsTable).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});
export type InsertChart = z.infer<typeof insertChartSchema>;
export type Chart = typeof chartsTable.$inferSelect;
